routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/clear', function () {
    $e = Artisan::call('cache:clear');
    $e1 = Artisan::call('config:cache');
    return redirect('/');
});

Route::get('/' , 'HomeController@index');
Route::get('/home' , 'HomeController@index');
Route::get('/about' ,'client\ClientController@about');
Route::get('/contact','client\ClientController@contact');
Route::post('/contact/send','client\ClientController@send');
Route::get('/photo','client\ClientController@photo');
Route::get('/video','client\ClientController@video');
Route::resource('/product', 'client\ProductController');
Route::get('/project/{id}', 'client\ClientController@project');
Route::get('/news/{id}', 'client\ClientController@news');
Route::resource('/category', 'client\CategoryController');
Route::group(['prefix' => '/administrator/grana'] ,function(){
    Auth::routes();
});


Route::group(['prefix' => 'admin' ,'middleware' => 'Administrator'], function () {

    Route::get('/', 'admin\AdminController@index');
    Route::get('/dashboard', 'admin\AdminController@index')->name('admin.dashboard');

    Route::DELETE('/Product/photo/{id}', 'admin\ProductController@destroyPhoto')->name('destroy.photo.product');
    Route::DELETE('/Project/photo/{id}', 'admin\ProjectController@destroyPhoto')->name('destroy.photo.project');

    Route::post('catalog/download', 'admin\CatalogController@getDownload');
    Route::get('catalog/upload', 'admin\CatalogController@upload')->name('catalog.upload');
    Route::post('catalog/upload/store', 'admin\CatalogController@store');
    Route::DELETE('catalog/destroy/{id}', 'admin\CatalogController@destroy');

    Route::get('photo/upload', 'admin\PhotoController@upload')->name('photo.upload');
    Route::post('photo/upload/store', 'admin\PhotoController@store');
    Route::DELETE('photo/destroy/{id}', 'admin\PhotoController@destroy');

    Route::post('video/download', 'admin\VideoController@getDownload');
    Route::get('video/upload', 'admin\VideoController@upload')->name('video.upload');
    Route::post('video/upload/store', 'admin\VideoController@store');
    Route::DELETE('video/destroy/{id}', 'admin\VideoController@destroy');

    Route::get('change/password', 'admin\AdminController@updateSecurityForm')->name('admin.passwordForm');
    Route::PATCH('{id}/change/password', 'admin\AdminController@updateSecurity')->name('admin.updateSecurity');

    Route::resource('/category', 'admin\CategoryController');
    Route::resource('/products', 'admin\ProductController');
    Route::resource('/about', 'admin\AboutController');
    Route::resource('/catalog', 'admin\CatalogController');
    Route::resource('/photo', 'admin\PhotoController');
    Route::resource('/video', 'admin\VideoController');
    Route::resource('/news', 'admin\NewsController');
    Route::resource('/projects', 'admin\ProjectController');
});

app/Http/Controllers/client/CatalogController.php
<?php

namespace App\Http\Controllers\client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CatalogController extends Controller
{
    //
}

app/Http/Controllers/client/CategoryController.php
<?php

namespace App\Http\Controllers\client;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    public function show($id)
    {
        $category = Category::find($id);
        $products = $category->products;
        return view('client.category' ,compact('products' ,'category'));
    }
}

app/Http/Controllers/client/ClientController.php
<?php

namespace App\Http\Controllers\client;

use App\Media;
use App\News;
use App\Project;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;

class ClientController extends Controller
{
    public function about()
    {
        $about = DB::table('abouts')->first();
        return view('client.about' ,compact('about'));
    }

    public function contact()
    {
        return view('client.contact');
    }

    public function send(Request $request)
    {
        $input = $request->all();
        $sender = $input['name'];
        $content = $input['description'];
        $email = $input['email'];
        Mail::send('client.send',['sender' => $sender ,'email' => $email ,'content' => $content ],function ($message){
            $message
                ->to('saradorri_90@yahoo.com')
                ->from('saradorri_90@yahoo.com')
                ->subject('تست');
        });
        return redirect()->back()->with('alert-success','ایمیل شما با موفقیت ارسال شد');
    }


    public function photo()
    {
        $photo = Media::where('type' , 'photo')->get();
        return view('client.photo' ,compact('photo'));
    }


    public function video()
    {
        $videos = Media::where('type' , 'video')->get();
        return view('client.video',compact('videos'));
    }

    public function project($id)
    {
        $project = Project::find($id);
        $lastProjects = Project::orderBy('created_at', 'desc')->limit(5)->get();
        return view('client.project',compact('project' ,'lastProjects'));
    }

    public function news($id)
    {
        $news = News::find($id);
        $lastNews = News::orderBy('created_at', 'desc')->limit(5)->get();
        return view('client.news',compact('news' ,'lastNews'));
    }



}

app/Http/Controllers/client/ProductController.php
<?php

namespace App\Http\Controllers\client;

use App\Category;
use App\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    public function show($id)
    {
        $lastProducts = Product::orderBy('created_at', 'desc')->limit(5)->get();
        $product = Product::find($id);
        return view('client.product' ,compact('product','lastProducts'));

    }
}

resources/views/client/about.blade.php
@extends('layouts.theme')
@section('title', 'گرانا بتن | درباره ما')

@section('content')

    <section id="contact-page">
        <div class="container-fluid">
            <div class="row">
                <div class="sp-page-title">
                    <div class="container">
                        <h3 class="sp-page-title-text">درباره ما</h3>
                    </div><!-- /.container -->
                </div><!-- /.sp-page-title -->
            </div><!-- /.Row -->
        </div><!-- /.container-fluid -->
        <div class="container" style="min-height: 400px;padding-top: 1em">
            <div class="about-page-title col-xs-12 col-sm-7">
                <h3 class="text-head" style="color: #333">{{ $about ? $about->subject : '' }}</h3>
                <div class="text-head-line"></div>
                <p class="text-justify">{{$about ? $about->description : ''}}</p>
            </div><!-- /.col-x-x -->
            <div class="col-xs-12 col-sm-5">
                <img class="img-responsive center-block" src="/image/about/{{$about ? $about->photo : ''}}" alt="image">
            </div><!-- /.col-x-x -->
        </div><!-- /.container -->
    </section>


@endsection

resources/views/client/category.blade.php
@extends('layouts.theme')
@section('title', 'گرانا بتن | محصولات')

@section('content')
    <section id="projects-page">
        <div class="container-fluid">
            <div class="row">
                <div class="sp-page-title">
                    <div class="container">
                        <h3 class="sp-page-title-text">{{$category->name}}</h3>
                    </div><!-- /.container -->
                </div><!-- /.sp-page-title -->
            </div><!-- /.Row -->
        </div><!-- /.container-fluid -->
        <div class="container" style="min-height: 400px;padding-top: 1em">
            <div class="row">
                <div class="col-xs-12 col-sm-9">
                    <div id="carousel" class="carousel carousel-product slide" data-ride="carousel">

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img src="/img/slider-2.jpg" alt="...">
                            </div><!-- /.item -->
                            <div class="item">
                                <img src="/img/slider-1.jpg" alt="...">
                            </div><!-- /.item -->
                        </div><!-- /.carousel-inner -->

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
                            <span class="fa fa-angle-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
                            <span class="fa fa-angle-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div><!-- /#carousel -->
                    <br>
                    <div class="products-page-title">
                        <h3 class="text-head" style="color: #333">{{ $category->name }}</h3>
                        <div class="text-head-line mb1"></div>
                        <p class="text-justify">
                            {{$category->description}}
                        </p>
                    </div>
                </div><!-- /.col-x-x -->
                <div class="col-xs-12 col-sm-3">
                    <div class="list-group list-group-products">
                        @if(isset($products))
                            @foreach($products as $product)
                                <a href="{{ route('product.show',$product->id)}}" class="list-group-item">{{$product->name}}</a>
                            @endforeach
                        @endif
                    </div><!-- /.list-group -->
                    <div class="jumbotron jumbotron-products " style="padding: 15px">
                        <h4 class="jumbotron-products-head">درباره شرکت</h4>
                        <div class="jumbotron-products-desc"><span class="fa fa-phone text-orange icon-align-left"></span>086-00000</div>
                        <div class="jumbotron-products-desc"><span class="fa fa-envelope-o text-orange icon-align-left"></span>info@gmail.com</div>
                        <div class="jumbotron-products-desc"><span class="fa fa-clock-o text-orange icon-align-left"></span>شنبه تا پنج شنبه</div>
                    </div><!-- /.jumbotron -->
                </div><!-- /.col-x-x -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </section>
@endsection

resources/views/client/contact.blade.php
@extends('layouts.theme')
@section('title', 'گرانا بتن | تماس با ما')

@section('content')
    <section id="contact-page">
        <div class="container-fluid">
            <div class="row">
                <div class="sp-page-title">
                    <div class="container">
                        <h3 class="sp-page-title-text">تماس با ما</h3>
                    </div><!-- /.container -->
                </div><!-- /.sp-page-title -->
            </div><!-- /.Row -->
            <div class="row">
                <img class="img-responsive center-block" style="width: 100%" src="/img/map.jpg" alt="map">
            </div><!-- /.Row -->
        </div><!-- /.container-fluid -->
        <div class="container">
            <div class="row">
                <div class="contact-page-head text-center">
                    <h3 class="contact-page-title">تماس با ما</h3>
                    <p class="contact-page-desc">لورم ایپسون متن ساختگی است که طراحان گرافیست و عکاسان از آن برای کارهای خود استفاده میکنند .</p>
                </div>
            </div><!-- /.Row -->
            <div class="row">
                <div class="col-xs-12 col-sm-4">
                    <div class="row mb1">
                        <div class="c-icon pull-right"><span class="fa fa-map-o"></span></div>
                        <div class="c-desc">
                            <h5 class="c-desc-head">آدرس ما</h5>
                            <div class="c-desc-t">ایران / تهران /...</div>
                        </div>
                    </div><!-- /item -->
                    <div class="row mb1">
                        <div class="c-icon pull-right"><span class="fa fa-envelope-o"></span></div>
                        <div class="c-desc">
                            <h5 class="c-desc-head">ایمیل ما</h5>
                            <div class="c-desc-t">info@gmail.com</div>
                        </div>
                    </div><!-- /item -->
                    <div class="row mb1">
                        <div class="c-icon pull-right"><span class="fa fa-phone"></span></div>
                        <div class="c-desc">
                            <h5 class="c-desc-head">تماس با ما</h5>
                            <div class="c-desc-t">021-000000</div>
                        </div>
                    </div><!-- /item -->
                </div><!-- /.col-x-x -->
                <div class="col-xs-12 col-sm-8">
                    <form action="{{url('/contact/send')}}" method="post" data-toggle="validator">
                        {{ csrf_field() }}
                        <!-- Text input-->
                        <div class="form-group has-feedback">
                            <input id="name" name="name" type="text" autocomplete="off" placeholder="نام و نام خانوادگی" class="form-control input-md" data-minlength="3" maxlength="30" data-error="نام و نام خانوادگی خود را وارد کنید." required>
                            <div class="col-xs-12 help-block with-errors"></div>
                        </div><!-- / Text input-->
                        <!-- Number input-->
                        <div class="form-group has-feedback">
                            <input id="email" name="email" type="email" autocomplete="off" placeholder="آدرس ایمیل" class="form-control input-md" data-error="آدرس ایمیل خود را وارد کنید." required>
                            <div class="help-block with-errors"></div>
                        </div><!-- / Number input-->
                        <div class="form-group has-feedback">
                            <textarea name="description" class="form-control" placeholder="متن پیام" rows="5" data-minlength="10" maxlength="1000" pattern="^[_a-z]{1,}$" data-error="متن پیام خود را وارد کنید." required></textarea>
                            <div class="col-xs-12 help-block with-errors"></div>
                        </div>
                        <div class="form-group has-feedback text-right">
                            <button type="submit" class="btn btn-info">ارسال</button>
                        </div>
                    </form>
                </div><!-- /.col-x-x -->
            </div><!-- /.Row -->
        </div><!-- /.container -->
    </section>
@endsection

@section('script')
    <script src="js/validator.min.js" defer="defer"></script>
@endsection

resources/views/client/news.blade.php
@extends('layouts.theme')
@section('title', 'گرانا بتن | اخبار')

@section('content')
    <section id="projects-page">
        <div class="container-fluid">
            <div class="row">
                <div class="sp-page-title">
                    <div class="container">
                        <h3 class="sp-page-title-text">{{ $news->name }}</h3>
                    </div><!-- /.container -->
                </div><!-- /.sp-page-title -->
            </div><!-- /.Row -->
        </div><!-- /.container-fluid -->
        <div class="container" style="min-height: 400px;padding-top: 1em">
            <div class="row">
                <div class="col-xs-12 col-sm-9">
                    <div id="carousel" class="carousel carousel-product slide" data-ride="carousel">

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img src="/image/news/{{$news->photo}}" alt="...">
                            </div><!-- /.item -->
                        </div><!-- /.carousel-inner -->

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
                            <span class="fa fa-angle-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
                            <span class="fa fa-angle-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div><!-- /#carousel -->
                    <br>
                    <div class="products-page-title">
                        <h3 class="text-head" style="color: #333">{{$news->name}}</h3>
                        <div class="text-head-line mb1"></div>
                        <p class="text-justify">
                            {{$news->description}}
                        </p>
                    </div>
                </div><!-- /.col-x-x -->
                <div class="col-xs-12 col-sm-3">
                    <h4>آخرین اخبار</h4>
                    <div class="list-group list-group-products">
                        @if(isset($lastNews))
                            @foreach($lastNews as $news)
                                <a href="{{url('/news', $news->id)}}" class="list-group-item">{{$news->name}}</a>
                            @endforeach
                        @endif
                    </div><!-- /.list-group -->
                    <div class="jumbotron jumbotron-products " style="padding: 15px">
                        <h4 class="jumbotron-products-head">درباره شرکت</h4>
                        <div class="jumbotron-products-desc"><span class="fa fa-phone text-orange icon-align-left"></span>086-00000</div>
                        <div class="jumbotron-products-desc"><span class="fa fa-envelope-o text-orange icon-align-left"></span>info@gmail.com</div>
                        <div class="jumbotron-products-desc"><span class="fa fa-clock-o text-orange icon-align-left"></span>شنبه تا پنج شنبه</div>
                    </div><!-- /.jumbotron -->
                </div><!-- /.col-x-x -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </section>
@endsection

resources/views/client/photo.blade.php
@extends('layouts.theme')
@section('title', 'گرانا بتن | گالری تصاویر')

@section('content')
    <section>
        <div class="container-fluid">
            <div class="row">
                <div class="sp-page-title">
                    <div class="container">
                        <h3 class="sp-page-title-text">گالری تصاویر</h3>
                    </div><!-- /.container -->
                </div><!-- /.sp-page-title -->
            </div><!-- /.Row -->
        </div><!-- /.container-fluid -->

        <div class="container" style="min-height: 400px;padding-top: 1em">
            <div class="row">
                @if(isset($photo))
                    @foreach($photo as $key=>$value)
                        <div class="col-xs-6 col-md-3 thumb">
                            <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-caption="{{$value->name}}" data-image="/media/photo/{{$value->path}}" data-target="#image-gallery">
                                <img class="img-responsive" src="/media/photo/{{$value->path}}" alt="Short alt text">
                            </a>
                        </div><!-- /col-x-x -->
                    @endforeach
                @endif
            </div><!-- /.row -->
        </div><!-- /.container -->
    </section>

    <!-- Modal -->
    <div class="modal fade" id="image-gallery" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span class="sr-only">بستن</span>
                        <span aria-hidden="true">×</span>
                    </button>
                    <h4 class="modal-title" id="image-gallery-title"></h4>
                </div>
                <div class="modal-body">
                    <img id="image-gallery-image" class="img-responsive center-block" src="">
                </div>
                <div class="modal-footer">

                    <div class="col-md-2">
                        <button type="button" class="btn btn-primary" id="show-previous-image"><span class="fa fa-arrow-right"></span></button>
                    </div>

                    <div class="col-md-8 text-justify" id="image-gallery-caption">

                    </div>

                    <div class="col-md-2">
                        <button type="button" id="show-next-image" class="btn btn-default"><span class="fa fa-arrow-left"></span></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /Modal -->

@endsection

@section('script')
    <script>
        $(document).ready(function(){

            loadGallery(true, 'a.thumbnail');

            //This function disables buttons when needed
            function disableButtons(counter_max, counter_current){
                $('#show-previous-image, #show-next-image').show();
                if(counter_max == counter_current){
                    $('#show-next-image').hide();
                } else if (counter_current == 1){
                    $('#show-previous-image').hide();
                }
            }

            /**
             *
             * @param setIDs        Sets IDs when DOM is loaded. If using a PHP counter, set to false.
             * @param setClickAttr  Sets the attribute for the click handler.
             */

            function loadGallery(setIDs, setClickAttr){
                var current_image,
                        selector,
                        counter = 0;

                $('#show-next-image, #show-previous-image').click(function(){
                    if($(this).attr('id') == 'show-previous-image'){
                        current_image--;
                    } else {
                        current_image++;
                    }

                    selector = $('[data-image-id="' + current_image + '"]');
                    updateGallery(selector);
                });

                function updateGallery(selector) {
                    var $sel = selector;
                    current_image = $sel.data('image-id');
                    $('#image-gallery-caption').text($sel.data('caption'));
                    $('#image-gallery-title').text($sel.data('title'));
                    $('#image-gallery-image').attr('src', $sel.data('image'));
                    disableButtons(counter, $sel.data('image-id'));
                }

                if(setIDs == true){
                    $('[data-image-id]').each(function(){
                        counter++;
                        $(this).attr('data-image-id',counter);
                    });
                }
                $(setClickAttr).on('click',function(){
                    updateGallery($(this));
                });
            }
        });
    </script>
@endsection

resources/views/client/product.blade.php
@extends('layouts.theme')
@section('title', 'گرانا بتن | محصولات')

@section('content')
    <section id="projects-page">
        <div class="container-fluid">
            <div class="row">
                <div class="sp-page-title">
                    <div class="container">
                        <h3 class="sp-page-title-text">{{$product->name}}</h3>
                    </div><!-- /.container -->
                </div><!-- /.sp-page-title -->
            </div><!-- /.Row -->
        </div><!-- /.container-fluid -->
        <div class="container" style="min-height: 400px;padding-top: 1em">
            <div class="row">
                <div class="col-xs-12 col-sm-9">
                    <div id="carousel" class="carousel carousel-product slide" data-ride="carousel">

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img src="/image/products/{{$product->photo}}" alt="...">
                            </div><!-- /.item -->
                        </div><!-- /.carousel-inner -->

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
                            <span class="fa fa-angle-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
                            <span class="fa fa-angle-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div><!-- /#carousel -->
                    <br>
                    <div class="products-page-title">
                        <h3 class="text-head" style="color: #333">{{$product->name}}</h3>
                        <div class="text-head-line mb1"></div>
                        <p class="text-justify">
                            {{$product->description}}
                        </p>
                    </div>
                </div><!-- /.col-x-x -->
                <div class="col-xs-12 col-sm-3">
                    <h4>آخرین محصولات</h4>
                    <div class="list-group list-group-products">
                        @if(isset($lastProducts))
                            @foreach($lastProducts as $p)
                                <a href="#" class="list-group-item">{{$p->name}}</a>
                            @endforeach
                        @endif
                    </div><!-- /.list-group -->
                    <div class="jumbotron jumbotron-products " style="padding: 15px">
                        <h4 class="jumbotron-products-head">درباره شرکت</h4>
                        <div class="jumbotron-products-desc"><span class="fa fa-phone text-orange icon-align-left"></span>086-00000</div>
                        <div class="jumbotron-products-desc"><span class="fa fa-envelope-o text-orange icon-align-left"></span>info@gmail.com</div>
                        <div class="jumbotron-products-desc"><span class="fa fa-clock-o text-orange icon-align-left"></span>شنبه تا پنج شنبه</div>
                    </div><!-- /.jumbotron -->
                </div><!-- /.col-x-x -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </section>
@endsection

resources/views/client/project.blade.php
@extends('layouts.theme')
@section('title', 'گرانا بتن | پروژه ها')

@section('content')
    <section id="projects-page">
        <div class="container-fluid">
            <div class="row">
                <div class="sp-page-title">
                    <div class="container">
                        <h3 class="sp-page-title-text">{{ $project->name }}</h3>
                    </div><!-- /.container -->
                </div><!-- /.sp-page-title -->
            </div><!-- /.Row -->
        </div><!-- /.container-fluid -->
        <div class="container" style="min-height: 400px;padding-top: 1em">
            <div class="row">
                <div class="col-xs-12 col-sm-9">
                    <div id="carousel" class="carousel carousel-product slide" data-ride="carousel">

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img src="/image/projects/{{$project->photo}}" alt="...">
                            </div><!-- /.item -->
                        </div><!-- /.carousel-inner -->

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
                            <span class="fa fa-angle-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
                            <span class="fa fa-angle-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div><!-- /#carousel -->
                    <br>
                    <div class="products-page-title">
                        <h3 class="text-head" style="color: #333">{{$project->name}}</h3>
                        <div class="text-head-line mb1"></div>
                        <p class="text-justify">
                            {{$project->description}}
                        </p>
                    </div>
                </div><!-- /.col-x-x -->
                <div class="col-xs-12 col-sm-3">
                    <h4>آخرین پروژه ها</h4>
                    <div class="list-group list-group-products">
                        @if(isset($lastProjects))
                            @foreach($lastProjects as $project)
                                <a href="{{url('/project', $project->id)}}" class="list-group-item">{{$project->name}}</a>
                            @endforeach
                        @endif
                    </div><!-- /.list-group -->
                    <div class="jumbotron jumbotron-products " style="padding: 15px">
                        <h4 class="jumbotron-products-head">درباره شرکت</h4>
                        <div class="jumbotron-products-desc"><span class="fa fa-phone text-orange icon-align-left"></span>086-00000</div>
                        <div class="jumbotron-products-desc"><span class="fa fa-envelope-o text-orange icon-align-left"></span>info@gmail.com</div>
                        <div class="jumbotron-products-desc"><span class="fa fa-clock-o text-orange icon-align-left"></span>شنبه تا پنج شنبه</div>
                    </div><!-- /.jumbotron -->
                </div><!-- /.col-x-x -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </section>
@endsection

resources/views/client/send.blade.php
<html>
<head></head>
<body style="direction: rtl;">
@php($mail=$email)
    <h1 style="direction: rtl;">نام فرستنده:</h1>
    <h1 style="direction: rtl;">{{$sender}}</h1>
    <h1 style="direction: rtl;">ایمیل فرستنده:</h1>
    <h1 style="direction: rtl;"><a href="mailto:{{$email}}">{{$email}}</a></h1>
    <h1 style="direction: rtl;">محتوای ایمیل ارسال شده:</h1>
    <p style="direction: rtl;">{{$content}}</p>
</body>
</html>