routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/clear', function () {
    $e = Artisan::call('cache:clear');
    $e1 = Artisan::call('config:cache');
    return redirect('/');
});

Route::get('/' , 'HomeController@index');
Route::get('/home' , 'HomeController@index');
Route::get('/about' ,'client\ClientController@about');
Route::get('/contact','client\ClientController@contact');
Route::post('/contact/send','client\ClientController@send');
Route::get('/photo','client\ClientController@photo');
Route::get('/video','client\ClientController@video');
Route::resource('/product', 'client\ProductController');
Route::get('/project/{id}', 'client\ClientController@project');
Route::get('/news/{id}', 'client\ClientController@news');
Route::resource('/category', 'client\CategoryController');
Route::group(['prefix' => '/administrator/grana'] ,function(){
    Auth::routes();
});


Route::group(['prefix' => 'admin' ,'middleware' => 'Administrator'], function () {

    Route::get('/', 'admin\AdminController@index');
    Route::get('/dashboard', 'admin\AdminController@index')->name('admin.dashboard');

    Route::DELETE('/Product/photo/{id}', 'admin\ProductController@destroyPhoto')->name('destroy.photo.product');
    Route::DELETE('/Project/photo/{id}', 'admin\ProjectController@destroyPhoto')->name('destroy.photo.project');

    Route::post('catalog/download', 'admin\CatalogController@getDownload');
    Route::get('catalog/upload', 'admin\CatalogController@upload')->name('catalog.upload');
    Route::post('catalog/upload/store', 'admin\CatalogController@store');
    Route::DELETE('catalog/destroy/{id}', 'admin\CatalogController@destroy');

    Route::get('photo/upload', 'admin\PhotoController@upload')->name('photo.upload');
    Route::post('photo/upload/store', 'admin\PhotoController@store');
    Route::DELETE('photo/destroy/{id}', 'admin\PhotoController@destroy');

    Route::post('video/download', 'admin\VideoController@getDownload');
    Route::get('video/upload', 'admin\VideoController@upload')->name('video.upload');
    Route::post('video/upload/store', 'admin\VideoController@store');
    Route::DELETE('video/destroy/{id}', 'admin\VideoController@destroy');

    Route::get('change/password', 'admin\AdminController@updateSecurityForm')->name('admin.passwordForm');
    Route::PATCH('{id}/change/password', 'admin\AdminController@updateSecurity')->name('admin.updateSecurity');

    Route::resource('/category', 'admin\CategoryController');
    Route::resource('/products', 'admin\ProductController');
    Route::resource('/about', 'admin\AboutController');
    Route::resource('/catalog', 'admin\CatalogController');
    Route::resource('/photo', 'admin\PhotoController');
    Route::resource('/video', 'admin\VideoController');
    Route::resource('/news', 'admin\NewsController');
    Route::resource('/projects', 'admin\ProjectController');
});

resources/views/layouts/admin_app.blade.php
<!DOCTYPE html>
<html lang="en" dir="rtl">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>

    <link href="{{asset('styles/bootstrap.min.css')}}" rel="stylesheet">
    {{--<link href="{{asset('styles/new-style.css')}}" rel="stylesheet">--}}
    <link href="{{asset('styles/sb-admin-2.css')}}" rel="stylesheet">
    <link href="{{asset('styles/font-awesome.min.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('styles/jquery.Bootstrap-PersianDateTimePicker.css')}}" rel="stylesheet" type="text/css">
    <script src="{{asset('scripts/jalaali.js')}}"></script>
    <script src="{{asset('scripts/jquery-2.2.4.min.js')}}"></script>
    <script src="{{asset('scripts/bootstrap.min.js')}}"></script>
    <script src="{{asset('scripts/jquery.Bootstrap-PersianDateTimePicker.js')}}"></script>
    <script src="{{asset('scripts/sb-admin-2.js')}}"></script>



    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    @yield('head')
</head>

<body>
<div id="wrapper">
    <nav class="navbar bg-primary navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header pull-left">
            {{--<a class="navbar-brand" href="{{ route('admin.dashboard') }}">{{ \Illuminate\Support\Facades\Auth::user()->name }}</a>--}}
        </div>
        <div class="navbar-header pull-left">
            <span>{{  ' امروز: ' . jDate::forge('today')->format('%d %B %Y')  }}</span>
</div>
        <div class="navbar-header pull-right">
            <a class="navbar-brand" href="/" target="_blank">مشاهده وب سایت</a>
        </div>
    </nav>
    <div id="page-wrapper">
      <div class="col-sm-3 col-sm-push-9" style="padding: 0 !important;">
        <div class="navbar-in sidebar" role="navigation" style="width: 100%;">
            <div class="sidebar-nav navbar-collapse collapse">
                <ul class="nav" id="side-menu">

                        <li data-toggle="collapse" data-target="#setting" class="collapsed remain">
                            <a href="#"><i class="fa fa-cogs"></i>  تنظیمات <span class="fa fa-caret-left pull-left"></span></a>
                        </li>

                        <ul class="nav nav-second-level collapse" id="setting">
                            <li>
                                <a href="{{ route('admin.passwordForm') }}"><span class="fa fa-key" >&nbsp;</span>تغییر رمز عبور</a>
                            </li>
                            <li>
                                <a href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    <span class="fa fa-sign-out" >&nbsp;</span>خروج
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    <li data-toggle="collapse" data-target="#category" class="collapsed remain">
                        <a href="#"><i class="fa fa-tasks"></i>  دسته بندی محصولات <span class="fa fa-caret-left pull-left"></span></a>
                    </li>

                    <ul class="nav nav-second-level collapse" id="category">
                        <li>
                            <a href="{{ route('category.create') }}">اضافه کردن دسته بندی جدید</a>
                        </li>
                        <li>
                            <a href="{{ route('category.index') }}">نمایش و ویرایش دسته بندی های موجود </a>
                        </li>
                    </ul>

                    <li data-toggle="collapse" data-target="#project" class="collapsed remain">
                        <a href="#"><i class="fa fa-cubes"></i>  پروژه ها <span class="fa fa-caret-left pull-left"></span></a>
                    </li>

                    <ul class="nav nav-second-level collapse" id="project">
                        <li>
                            <a href="{{ route('projects.create') }}">اضافه کردن پروژه جدید</a>
                        </li>
                        <li>
                            <a href="{{ route('projects.index') }}">نمایش و ویرایش پروژه های موجود </a>
                        </li>
                    </ul>


                    <li data-toggle="collapse" data-target="#news" class="collapsed remain">
                        <a href="#"><i class="fa fa-newspaper-o"></i> اخبار  <span class="fa fa-caret-left pull-left"></span></a>
                    </li>

                    <ul class="nav nav-second-level collapse" id="news">
                        <li>
                            <a href="{{ route('news.create') }}">اضافه کردن اخبار</a>
                        </li>
                        <li>
                            <a href="{{ route('news.index') }}">نمایش و ویرایش اخبار </a>
                        </li>
                    </ul>

                    <li data-toggle="collapse" data-target="#products" class="collapsed remain">
                        <a href="#"><i class="fa fa-barcode"></i> محصولات  <span class="fa fa-caret-left pull-left"></span></a>
                    </li>

                    <ul class="nav nav-second-level collapse" id="products">
                        <li>
                            <a href="{{ route('products.create') }}">اضافه کردن محصول جدید</a>
                        </li>
                        <li>
                            <a href="{{ route('products.index') }}">نمایش و ویرایش محصولات موجود </a>
                        </li>
                    </ul>


                    <li data-toggle="collapse" data-target="#catalog" class="collapsed remain">
                        <a href="#"><i class="fa fa-file"></i> کاتالوگ <span class="fa fa-caret-left pull-left"></span></a>
                    </li>

                    <ul class="nav nav-second-level collapse" id="catalog">

                        <li>
                            <a href="{{ route('catalog.index') }}">نمایش کاتالوگ ها </a>
                        </li>

                        <li>
                            <a href="{{ route('catalog.upload') }}">بارگذاری کاتالوگ </a>
                        </li>
                    </ul>

                    <li data-toggle="collapse" data-target="#photo" class="collapsed remain">
                        <a href="#"><i class="fa fa-photo"></i> گالری تصاویر <span class="fa fa-caret-left pull-left"></span></a>
                    </li>

                    <ul class="nav nav-second-level collapse" id="photo">

                        <li>
                            <a href="{{ route('photo.index') }}">نمایش تصاویر </a>
                        </li>

                        <li>
                            <a href="{{ route('photo.upload') }}">بارگذاری تصویر </a>
                        </li>
                    </ul>

                    <li data-toggle="collapse" data-target="#video" class="collapsed remain">
                        <a href="#"><i class="fa fa-video-camera"></i> گالری ویدئو <span class="fa fa-caret-left pull-left"></span></a>
                    </li>

                    <ul class="nav nav-second-level collapse" id="video">

                        <li>
                            <a href="{{ route('video.index') }}">نمایش ویدئوها </a>
                        </li>

                        <li>
                            <a href="{{ route('video.upload') }}">بارگذاری ویدئو </a>
                        </li>
                    </ul>

                    <li data-toggle="collapse" data-target="#about" class="collapsed remain">
                        <a href="#"><i class="fa fa-info-circle"></i> درباره ما <span class="fa fa-caret-left pull-left"></span></a>
                    </li>

                    <ul class="nav nav-second-level collapse" id="about">
                        <li>
                            <a href="{{ route('about.create') }}">ایجاد </a>
                        </li>
                        <li>
                            <a href="{{ route('about.index') }}">مشاهده و ویرایش </a>
                        </li>
                    </ul>

                </ul>
            </div>
        </div>
    </div>

    <div class="col-sm-9 col-sm-pull-3" style="padding: 0 0 0 15px !important;">
        <div id="page-wrapper" style="border-radius: 14px;">
            <div class="row">
                <div class="col-sm-12">
                    <h2 class="page-header">@yield('head-content')</h2>
                </div>
            </div>
            <div class="col-sm-12">
                @yield('content')
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
</div>
<script src="{{asset('scripts/jquery-2.2.4.min.js')}}"></script>
@yield('script')

</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'گرانا بتن') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        مشاهده سایت
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">ورود</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/theme.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@yield('title')</title>
    <!-- Bootstrap core CSS -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<nav class="navbar navbar-default" style="margin-bottom: 0">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">گرانا بتن</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">صفحه اصلی</a></li>
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">محصولات<i class="caret icon-align-right"></i></a>
                    <ul class="dropdown-menu multi-level">
                        @if(isset($roots))
                            @foreach($roots as $key=>$value)
                                @if(sizeof($value->getImmediateDescendants())== 0)
                                    <li><a href="{{url('/category', $value->id)}}">{{$value->name}}</a></li>
                                @else
                                <li class="dropdown-submenu">
                                    <a href="{{url('/category', $value->id)}}" class="dropdown-toggle" data-toggle="dropdown">{{$value->name}}<i class="caret"></i></a>
                                    <ul class="dropdown-menu">
                                        @foreach($value->getImmediateDescendants() as $child)
                                            @if(sizeof($child->getImmediateDescendants())== 0)
                                                <li><a href="{{url('/category', $child->id)}}">{{ $child->name }}</a></li>
                                            @else
                                            <li class="dropdown-submenu">
                                                <a href="{{url('/category', $child->id)}}" class="dropdown-toggle" data-toggle="dropdown">{{ $child->name }}<i class="caret"></i></a>
                                                <ul class="dropdown-menu">
                                                    @foreach($child->getImmediateDescendants() as $children)
                                                        @if(sizeof($children->getImmediateDescendants())== 0)
                                                            <li><a href="{{url('/category', $children->id)}}">{{ $children->name }}</a></li>
                                                        @else
                                                            <li class="dropdown-submenu">
                                                                <a href="{{url('/category', $children->id)}}" class="dropdown-toggle" data-toggle="dropdown">{{ $children->name }}<i class="caret"></i></a>
                                                                <ul class="dropdown-menu">
                                                                    <li><a href="{{url('/category', $children->id)}}">{{ $children->name }}</a></li>
                                                                </ul>
                                                            </li>
                                                        @endif
                                                    @endforeach
                                                </ul>
                                            </li>
                                            @endif
                                        @endforeach
                                    </ul>
                                </li>
                                @endif
                            @endforeach
                        @endif
                    </ul><!-- /.dropdown-menu -->
                </li>
                <li><a href="#">بازرگانی</a></li>
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">چندرسانه ای<i class="caret icon-align-right"></i></a>
                    <ul class="dropdown-menu multi-level">
                        <li><a href="{{ url('/photo') }}">گالری تصاویر</a></li>
                        <li><a href="{{ url('/video') }}">گالری فیلم</a></li>
                    </ul><!-- /.dropdown-menu -->
                </li>
                <li><a href="{{ url('/about') }}">درباره ما</a></li>
                <li><a href="{{ url('/contact') }}">تماس با ما</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

@yield('content')


<footer id="footer">
    <div class="container">
        <div class="row mb1" style="">
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="footer-box">
                    <h5 class="footer-box-head">درباره گرانا بتن</h5>
                    <p class="text-justify">
                        لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها
                        و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و
                        کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.
                    </p>
                </div><!-- /.col-x-x -->
            </div><!-- /col-x-x -->
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="footer-box">
                    <h5 class="footer-box-head">آخرین اخبار</h5>
                    <ul class="list-unstyled footer-box-list-note">
                        @if(isset($news))
                            @foreach($news as $key=>$value)
                                <li><a href="{{url('/news' ,$value->id)}}">{{$value->name}}</a></li>
                            @endforeach
                        @endif
                    </ul>
                </div><!-- /.col-x-x -->
            </div><!-- /col-x-x -->
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="footer-box">
                    <h5 class="footer-box-head">راه های تماس با ما</h5>
                    <ul class="list-unstyled footer-box-list-note">
                        <li><span class="fa fa-phone text-orange icon-align-left"></span>086-00000</li>
                        <li><span class="fa fa-envelope-o text-orange icon-align-left"></span>info@gmail.com</li>
                        <li><span class="fa fa-clock-o text-orange icon-align-left"></span>شنبه تا پنج شنبه</li>
                    </ul>
                </div><!-- /.col-x-x -->
            </div><!-- /col-x-x -->
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="footer-box">
                    <h5 class="footer-box-head">گرانا بتن</h5>
                    <img class="center-block img-responsive" style="max-width: 140px" src="/img/logo.jpg" alt="image">
                </div><!-- /.col-x-x -->
            </div><!-- /col-x-x -->
        </div><!-- /.Row -->
        <div class="row">
            <div style="border-top: 1px solid white;margin-top: 1em;padding-top: 0.5em">
                <div class="col-xs-12 col-sm-7">تمامی حقوق مادی و معنوی سایت برای <a href="/">گرانا بتن</a> محفوظ میباشد .</div>
                <ul class="list-inline col-xs-12 col-sm-5 footer-social">
                    <li class="footer-social-list"><a href="#"><span class="fa fa-android"></span></a></li>
                    <li class="footer-social-list"><a href="#"><span class="fa fa-send"></span></a></li>
                    <li class="footer-social-list"><a href="#"><span class="fa fa-instagram"></span></a></li>
                    <li class="footer-social-list"><a href="#"><span class="fa fa-google-plus"></span></a></li>
                </ul>
            </div>
        </div><!-- /.Row -->
    </div><!-- /.container -->
</footer><!-- /#footer -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/js/jquery.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/custom.js"></script>
@yield('script')
</body>
</html>